---
title: "Slides"
output:
  slidy_presentation:
  css: C:/Users/la-temp/Documents/R/win-library/4.0/setbuildr/css/style.css
---
  
  ```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, results = 'asis')
```
## 10000 Reasons Chorus
Bless the Lord O my soul<br>
O my soul<br>
Worship His Holy name<br>
Sing like never before<br>
O my soul<br>
I’ll worship Your Holy name<br>

## 10000 Reasons Verse 1a
The sun comes up<br>
It’s a new day dawning<br>
It’s time to sing Your song again<br>

## 10000 Reasons Verse 1b
Whatever may pass<br>
And whatever lies before me<br>
Let me be singing<br>
When the evening comes<br>

## 10000 Reasons Chorus
Bless the Lord O my soul<br>
O my soul<br>
Worship His Holy name<br>
Sing like never before<br>
O my soul<br>
I’ll worship Your Holy name<br>

## 10000 Reasons Verse 2a
You’re rich in love<br>
And You’re slow to anger<br>
Your name is great<br>

## 10000 Reasons Verse 2b
And Your heart is kind<br>
For all Your goodness<br>
I will keep on singing<br>
Ten thousand reasons<br>
For my heart to find<br>

## 10000 Reasons Chorus
Bless the Lord O my soul<br>
O my soul<br>
Worship His Holy name<br>
Sing like never before<br>
O my soul<br>
I’ll worship Your Holy name<br>

## 10000 Reasons Verse 3a
And on that day<br>
When my strength is failing<br>
The end draws near<br>
And my time has come<br>

## 10000 Reasons Verse 3b
Still my soul will<br>
Sing Your praise unending<br>
Ten thousand years<br>
And then forevermore<br>

## 10000 Reasons Chorus (Last)
Bless the Lord O my soul<br>
O my soul<br>
Worship His Holy name<br>
Sing like never before<br>
O my soul<br>
I’ll worship Your Holy name<br>

#### Last

## End of Song
 

## All Creatures of Our God and King Verse 1
All creatures of our God and King<br>
lift up your voice and with us sing<br>
O praise ye! Alleluia<br>
O brother sun with golden beam<br>
O sister moon with silver gleam<br>
O praise ye! O praise ye<br>
Alleluia! Alleluia! Alleluia<br>

## All Creatures of Our God and King Verse 2
O brother wind, air, clouds, and rain<br>
by which all creatures ye sustain<br>
O praise ye! Alleluia<br>
Thou rising morn, in praise rejoice<br>
ye lights of evening, find a voice<br>
O praise ye! O praise ye<br>
Alleluia! Alleluia! Alleluia<br>

## All Creatures of Our God and King Verse 3
O sister water, flowing clear<br>
make music for thy Lord to hear<br>
Alleluia! Alleluia<br>
O brother fire who lights the night<br>
providing warmth, enhancing sight<br>
O praise ye! O praise ye<br>
Alleluia! Alleluia! Alleluia<br>

## All Creatures of Our God and King Verse 4
Dear mother earth, who day by day<br>
unfoldest blessings on our way<br>
Alleluia! Alleluia<br>
The flowers and fruits that in thee grow<br>
let them God's glory also show<br>
O praise ye! O praise ye<br>
Alleluia! Alleluia! Alleluia<br>

## All Creatures of Our God and King Verse 5
All ye who are of tender heart<br>
forgiving others, take your part<br>
O praise ye! Alleluia<br>
Ye who long pain and sorrow bear<br>
praise God and on him cast your care<br>
O praise ye! O praise ye<br>
Alleluia! Alleluia! Alleluia<br>

## All Creatures of Our God and King Verse 6
And thou, our sister, gentle death<br>
waiting to hush our latest breath<br>
Alleluia! Alleluia<br>
Thou leadest home the child of God<br>
and Christ our Lord the way has trod<br>
O praise ye! O praise ye<br>
Alleluia! Alleluia! Alleluia<br>

## All Creatures of Our God and King Verse 7 (Last)
Let all things their Creator bless<br>
and worship him in humbleness<br>
O praise ye! Alleluia<br>
Praise, praise the Father, praise the Son<br>
and praise the Spirit, Three in One<br>
O praise ye! O praise ye<br>
Alleluia! Alleluia! Alleluia<br>

#### Last

## End of Song
 
 


## Talking Time
Talking Time
